import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About GenStub — Free Pay Stub Generator for 12 Countries',
  description: 'Learn about GenStub, our mission to provide free, accurate pay stub and salary slip generation for workers and employers worldwide.',
}

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="mb-12">
        <p className="text-teal-brand text-sm font-semibold uppercase tracking-widest mb-3">About us</p>
        <h1 className="font-fraunces text-4xl sm:text-5xl text-navy font-semibold mb-6 leading-tight">
          Pay stubs should not cost money to generate.
        </h1>
        <p className="text-charcoal/70 text-lg leading-relaxed">
          GenStub was built with one belief: generating a pay stub or salary slip should never cost the person who needs it most.
        </p>
      </div>

      <div className="prose prose-lg text-charcoal/70 space-y-6">
        <p>Most pay stub generators claim to be free. They are not. They put you through a five-minute form and then tell you it costs $8.99 to download what you just built. Some show a watermarked preview and charge to remove it. Others charge per stub without making the pricing clear upfront.</p>

        <p>GenStub is genuinely free. We generate our revenue through non-intrusive Google AdSense advertisements, which means you can generate professional, watermark-free documents at no cost, forever.</p>

        <h2 className="font-fraunces text-2xl text-navy font-semibold mt-8 mb-4">Why 12 countries?</h2>
        <p>Every existing pay stub tool targets the US market exclusively. But payroll workers in India, Kenya, Nigeria, the Philippines, and dozens of other countries need the same thing — a professional, accurate payslip — and nothing serves them well.</p>

        <p>We built GenStub with full support for 12 countries from day one, each with their own statutory deduction structure, current rates, and correct terminology. Kenya's payslip uses SHA (not the old NHIF). Nigeria's PAYE uses the NTA 2025 bands. The UAE format correctly shows zero income tax for expatriates. These details matter.</p>

        <h2 className="font-fraunces text-2xl text-navy font-semibold mt-8 mb-4">Our commitment to accuracy</h2>
        <p>Payroll legislation changes. We review and update deduction rates for all supported countries whenever statutory changes take effect. Our content team monitors official sources — HMRC, SARS, KRA, the Bureau of Internal Revenue, the FBR, and others — so that GenStub reflects current law, not last year's rules.</p>

        <p>We strongly recommend verifying generated documents against official guidance for your specific situation. GenStub provides accurate calculations based on standard inputs, but individual circumstances — multiple jobs, special tax codes, retrospective adjustments — may differ from the auto-calculated output. The manual override option is there for exactly this reason.</p>

        <h2 className="font-fraunces text-2xl text-navy font-semibold mt-8 mb-4">Document integrity</h2>
        <p>Every document generated by GenStub is designed to meet the standards that banks, landlords, and lenders expect. This means professional typography, a unique document reference number, the net pay amount expressed in words, correctly itemised deductions, and a footer stating that the document is computer-generated. No watermarks. No branding stamps. Documents that look like they came from a proper payroll system.</p>

        <p>GenStub documents are intended for legitimate payroll record-keeping, income verification, and employment documentation purposes.</p>
      </div>

      <div className="mt-12 pt-8 border-t border-cream-dark">
        <p className="text-charcoal/60 text-sm mb-4">Have a question or feedback?</p>
        <Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 bg-navy text-white font-semibold rounded-xl hover:bg-navy-light transition-all">
          Contact us →
        </Link>
      </div>
    </div>
  )
}
